=== VelislavKL/VideoGames/VideoGames/VideoGames/AppData/VideoGamesDTD.dtd
<?xml encoding="UTF-8"?>

<!ELEMENT Games (Name,Country?,Publisher,Website,Description?,License?,
                 Languages?,ReleaseDate,Price,Media?,GameSize,Platform,
                 Genre?,Players?,Type?,ContentRating?,RequirementsList?)>
<!ATTLIST Games
  xmlns CDATA #FIXED ''
  CatalogRating CDATA #REQUIRED
  IsAvailable NMTOKEN #REQUIRED>

<!ELEMENT Name (#PCDATA)>
<!ATTLIST Name
  xmlns CDATA #FIXED ''>

<!ELEMENT Country (#PCDATA)>
<!ATTLIST Country
  xmlns CDATA #FIXED ''>

<!ELEMENT Publisher (#PCDATA)>
<!ATTLIST Publisher
  xmlns CDATA #FIXED ''>

<!ELEMENT Website (#PCDATA)>
<!ATTLIST Website
  xmlns CDATA #FIXED ''>

<!ELEMENT Description (#PCDATA)>
<!ATTLIST Description
  xmlns CDATA #FIXED ''>

<!ELEMENT License (#PCDATA)>
<!ATTLIST License
  xmlns CDATA #FIXED ''>

<!ELEMENT Languages (#PCDATA)>
<!ATTLIST Languages
  xmlns CDATA #FIXED ''>

<!ELEMENT ReleaseDate (#PCDATA)>
<!ATTLIST ReleaseDate
  xmlns CDATA #FIXED ''>

<!ELEMENT Price (#PCDATA)>
<!ATTLIST Price
  xmlns CDATA #FIXED ''>

<!ELEMENT Media (#PCDATA)>
<!ATTLIST Media
  xmlns CDATA #FIXED ''>

<!ELEMENT GameSize (#PCDATA)>
<!ATTLIST GameSize
  xmlns CDATA #FIXED ''>

<!ELEMENT Platform (#PCDATA)>
<!ATTLIST Platform
  xmlns CDATA #FIXED ''>

<!ELEMENT Genre (#PCDATA)>
<!ATTLIST Genre
  xmlns CDATA #FIXED ''>

<!ELEMENT Players (#PCDATA)>
<!ATTLIST Players
  xmlns CDATA #FIXED ''>

<!ELEMENT Type (#PCDATA)>
<!ATTLIST Type
  xmlns CDATA #FIXED ''>

<!ELEMENT ContentRating (AgeLevel?,System?)>
<!ATTLIST ContentRating
  xmlns CDATA #FIXED ''
  GameId CDATA #REQUIRED>

<!ELEMENT RequirementsList (Requirements*)+>
<!ATTLIST RequirementsList
  xmlns CDATA #FIXED ''>

<!ELEMENT AgeLevel (#PCDATA)>
<!ATTLIST AgeLevel
  xmlns CDATA #FIXED ''>

<!ELEMENT System (#PCDATA)>
<!ATTLIST System
  xmlns CDATA #FIXED ''>

<!ELEMENT Requirements (OperatingSystem?,Cpu?,Ram?,Graphics?,Storage?,
                        DirectX?,InternetNeed?,RequirementsType?)>
<!ATTLIST Requirements
  xmlns CDATA #FIXED ''
  GameId CDATA #REQUIRED>

<!ELEMENT OperatingSystem (#PCDATA)>
<!ATTLIST OperatingSystem
  xmlns CDATA #FIXED ''>

<!ELEMENT Cpu (#PCDATA)>
<!ATTLIST Cpu
  xmlns CDATA #FIXED ''>

<!ELEMENT Ram (#PCDATA)>
<!ATTLIST Ram
  xmlns CDATA #FIXED ''>

<!ELEMENT Graphics (#PCDATA)>
<!ATTLIST Graphics
  xmlns CDATA #FIXED ''>

<!ELEMENT Storage (#PCDATA)>
<!ATTLIST Storage
  xmlns CDATA #FIXED ''>

<!ELEMENT DirectX (#PCDATA)>
<!ATTLIST DirectX
  xmlns CDATA #FIXED ''>

<!ELEMENT InternetNeed (#PCDATA)>
<!ATTLIST InternetNeed
  xmlns CDATA #FIXED ''>

<!ELEMENT RequirementsType (#PCDATA)>
<!ATTLIST RequirementsType
  xmlns CDATA #FIXED ''>

=== VelislavKL/VideoGames/VideoGames/VideoGames/AppData/xml-2052.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE Games SYSTEM "VideoGamesDTD.dtd">
<Games CatalogRating="4.8" IsAvailable="false">
  <Name>Counter-Strike: Global Offensive</Name>
  <Publisher>Valve</Publisher>
  <Website>www.csgo.com</Website>
  <Description>Counter-Strike: Global Offensive (CS:GO) е следващата стъпка в еволюцията на класическият отборен геймплей, който се превърна в световна сензация преди 12 години с дебюта на Counter Strike. CS:GO предлага обновени класически карти (dust, aztec и др.), но включва и нови геймплей режими, оръжия и персонажи.
С появата си през август 1999 модификацията на Half-Life e изненада за цялата гейминг индустрия и бързо се превръща в най-играното онлайн заглавие. До ден днешен Counter-Strike продължава да е сред най-популярните игри, включително на турнирно ниво, а поредицата е продала над 25 милиона копия.
CS: GO продължава легендата.</Description>
  <ReleaseDate>2012-07-07T00:00:00</ReleaseDate>
  <Price>29.95</Price>
  <GameSize>15.65 GB</GameSize>
  <Platform>PC</Platform>
  <Genre>Шутер</Genre>
  <ContentRating GameId="2052">
    <AgeLevel>3</AgeLevel>
    <System>PEGI</System>
  </ContentRating>
  <RequirementsList>
    <Requirements GameId="2052">
      <OperatingSystem>Windows 7/Vista/XP/Windows 8</OperatingSystem>
      <Cpu>Intel Core 2 Duo E6600 / AMD Phenom™ X3 8750</Cpu>
      <Ram>1GB XP / 2GB Vista, Windows 7</Ram>
      <Graphics>256 MB с Pixel Shader 3.0</Graphics>
      <Storage>20 GB</Storage>
      <DirectX>11</DirectX>
      <InternetNeed>true</InternetNeed>
      <RequirementsType>минимални</RequirementsType>
    </Requirements>
  </RequirementsList>
</Games>
